### ISSUE TITLE
App crashes - Scroll issue

### ISSUE THREAD

**Issue by pradeepb28** [Renset/macai#2]
![CleanShot 2023-03-26 at 14 18 33](https://user-images.githubusercontent.com/6823101/227765221-0ed64a26-c3d2-4a48-bb8c-2fa0eed9da8f.png)

**Comment by Renset** [comment]
Hey @pradeepb28 please provide bit more info: given the information you provided, I couldn't determine what issue you faced yet. 
If this an App crash, please describe the repro steps.
If you have scrolling issues, please describe what issues you're observing.
Also, please add information about your platform (M1/M2 or Intel Mac), OS version.

**Comment by pradeepb28** [comment]
no specific steps ...as I continuously type in text field it just crashes. I am on macOS 13.2. @Renset
