### ISSUE TITLE
[Feature] Google’s Gemini API support 

### ISSUE THREAD

**Issue by ThunderRuler** [Renset/macai#21]
Just as title describes. It would be great to select Google’s Gemini 1.5 pro or 1.5 flash as a possible model to choose from.

**Comment by Renset** [comment]
Hey @ThunderRuler, that's a good idea. I'll take this to work

**Comment by Renset** [comment]
@ThunderRuler Google Gemini support has been added in [v2.0.0-beta.1](https://github.com/Renset/macai/releases/tag/v2.0.0-beta.1), so closing this ticket for now.
