### ISSUE TITLE
Feature request: Custom system messages

### ISSUE THREAD

**Issue by envieme** [Renset/macai#24]
It would be nice to have the ability to switch to custom system messages once a new chat is opened. The system messges can be saved as a list. For example I should be able to create Custom experts like Medical Expert, IT expert, Stock trader, JS Programmer. Each will have its own system message. When opening a new chat, i should be able to select one of these in the edit system message field.

**Comment by Renset** [comment]
Hey @envieme,
nice idea - I was planning to implement it and track this feature in the related project. Thanks for the validation, I'll try to prioritize it in version 2 that I'm working on now.

**Comment by Renset** [comment]
@envieme the feature is basically implemented and will be released soon with v2. The feature's draft name is 'AI Personas':
![CleanShot 2024-09-09 at 01 18 54@2x](https://github.com/user-attachments/assets/3ccf1f20-1f44-4ebc-8990-e05f970cb88e)
![CleanShot 2024-09-09 at 01 19 19@2x](https://github.com/user-attachments/assets/ac009d86-40a0-4f5d-bf0b-69ebd3108d8f)

**Comment by envieme** [comment]
Oh this is great to see and hear. Can't wait for v2.

2024-09-08T22:22:10Z Renat ***@***.***>:

**Comment by envieme** [comment]
Hi, when will you release the 2.0? Thanks.

**Comment by Renset** [comment]
Hi @envieme, I'm under an increased workload at my job, but hopefully I'll be able to publish a release candidate in November

**Comment by Renset** [comment]
Hey @envieme, the version [v2-alpha.1 is out](https://github.com/Renset/macai/releases/tag/v2.0.0-alpha.1) with customizable AI personas. Feel free to check ;)

**Comment by envieme** [comment]
Awesome, thanks for this. It is really good. I noticed when deleting chats
from sidebar by rightclick it many times crashes. Also do you plan to
introduce pasting / uploading images? That would be great.

**Comment by envieme** [comment]
Some feedback:

As I said while deleting chats from sidebar, app seems to crash often

I would like to customize font size of chats and app

A clear chat button at topbar next to new chat will be useful to clear all the messages in a chat and start with no context in the same chat

Ability to send images

Ability to resize custom system message text field while editing it

**Comment by Renset** [comment]
App crashes on deleting chats should be fixed now in https://github.com/Renset/macai/releases/tag/v2.0.0-beta.1
