### ISSUE TITLE
[Feature] Clear chat button

### ISSUE THREAD

**Issue by Renset** [Renset/macai#30]
A clear chat button at topbar next to new chat will be useful to clear all the messages in a chat and start with no context in the same chat

**Comment by Renset** [comment]
@envieme this button has been added in https://github.com/Renset/macai/releases/tag/v2.0.0-rc.1 into context menu. Planning to add some hotkeys and/or move to the toolbar in the future versions.

**Comment by envieme** [comment]
Yes, this is good. Thanks.
