### ISSUE TITLE
Feature Request: Option to remove Network request timeout.

### ISSUE THREAD

**Issue by wedlj2094** [Renset/macai#39]
I sometimes use LLMs to translate long text, which makes AI's response lengthy, which increases latency of a response. 
This sometimes falsely triggers Network request timeout on macai.
Yes, I could mitigate this issue by using stream response, but when using stream response with Gemini, Gemini's response tends to cut off before spitting out whole response. So, some times I have to disable stream response. 
**(This is probably not macai issue, this also occurs on official Google ai studio website. For some ungodly reason)**

It would be great if there is a way to disable Network request timeout when not using stream response.

![Screenshot 2024-12-13 at 1 49 09 PM](https://github.com/user-attachments/assets/e5cd4f87-a11e-42aa-8748-a11cf8607394)

**Comment by Renset** [comment]
@wedlj2094 good catch, I think I had the same problem with Claude when waiting for a really long response. Adjusting the timeouts should be very easy, so I'll try to fix this problem until the next release.

**Comment by Renset** [comment]
@wedlj2094 should be fixed now in https://github.com/Renset/macai/releases/tag/v2.0.0-rc.1
