### ISSUE TITLE
Feature: Add pagination

### ISSUE THREAD

**Issue by pradeepb28** [Renset/macai#8]
It would be great if the chat is loaded from core data using pagination, this helps ensure  long chats are loaded in reasonable time.

**Comment by pradeepb28** [comment]
when users have 2-3 chats it is fine no need of pagination but when users have 10 chats and each chat has more than 50 messages, it will be noticeably slow.

Also by the way, apps with feeds or chat kinda use-cases uses pagination by default as a good practice :)

**Comment by Renset** [comment]
I'm not sure the pagination is a good practice for desktop apps, at least for most cases, but just in case may you provide some examples? And what pagination did you mean, pagination for messages or pagination for chats?

**Comment by Renset** [comment]
I am closing this ticket for now, but this issue can be re-opened once the example is provided
